// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day3.Models;

public partial class Employee
{
    [Key]
    public int EmpID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EmpName { get; set; }

    public short? OrgLevel { get; set; }
}