// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day3.Models;

[Keyless]
public partial class student_note
{
    [StringLength(50)]
    public string username { get; set; }

    public DateOnly? Date { get; set; }

    [StringLength(100)]
    public string Note { get; set; }
}